[
	{
	    "id": "barbarian",
	    "name": "Barbarian",
	    "hp": 10,
	    "skills": 5,
	    "kom": "Varies",
	    "kdm": "Con",
	    "ab": "High",
	    "highSaves": ["Fort", "Will"],
	    "lowSave": "Ref",
	    "fastTrack": ["Path of the Ancestors"],
	    "mediumTrack": ["Rage", "Dervish"],
	    "slowTrack": ["Path of Destruction"]
	},
	{
	    "id": "monk",
	    "name": "Monk",
	    "hp": 8,
	    "skills": 6,
	    "kom": "Wis",
	    "kdm": "Con",
	    "ab": "High",
	    "highSaves": ["Any", "Any"],
	    "lowSave": "Any",
	    "fastTrack": ["Discipline of the Dragon"],
	    "mediumTrack": ["Discipline of the Serpent"],
	    "slowTrack": ["Discipline of the Crane"]
	},
	{
	    "id": "paladin",
	    "name": "Paladin",
	    "hp": 10,
	    "skills": 5,
	    "kom": "Str",
	    "kdm": "Cha",
	    "ab": "High",
	    "highSaves": ["Fort", "Will"],
	    "lowSave": "Ref",
	    "fastTrack": ["Judgement"],
	    "mediumTrack": ["Bastion", "Heroica", "Smiting", "Virtue"],
	    "slowTrack": ["Bastion", "Heroica", "Smiting", "Virtue"]
	},
	{
	    "id": "ranger",
	    "name": "Ranger",
	    "hp": 10,
	    "skills": 6,
	    "kom": "Dex",
	    "kdm": "Int",
	    "ab": "High",
	    "highSaves": ["Fort", "Ref"],
	    "lowSave": "Will",
	    "fastTrack": ["Battles Tempering"],
	    "mediumTrack": ["Professional Soldier"],
	    "slowTrack": ["A Reign of Arrows", "Iron Magi"]
	},
	{
	    "id": "rogueAB",
	    "name": "Rogue High AB",
	    "hp": 8,
	    "skills": 6,
	    "kom": "Varies",
	    "kdm": "Varies",
	    "ab": "High",
	    "highSaves": ["Ref", "Any"],
	    "lowSave": "Any",
	    "fastTrack": ["Esoterica Radica"],
	    "mediumTrack": ["Assassin", "Swashbuckler", "Demo Man"],
	    "slowTrack": ["Acrobatic Adept", "I Am Ten Ninjas", "Fortune's Friend"]
	},
	{
	    "id": "rogueSkills",
	    "name": "Rogue Extra Skills",
	    "hp": 8,
	    "skills": 8,
	    "kom": "Varies",
	    "kdm": "Varies",
	    "ab": "Low",
	    "highSaves": ["Ref", "Any"],
	    "lowSave": "Any",
	    "fastTrack": ["Esoterica Radica"],
	    "mediumTrack": ["Assassin", "Swashbuckler", "Demo Man"],
	    "slowTrack": ["Acrobatic Adept", "I Am Ten Ninjas", "Fortune's Friend"]
	},
	{
	    "id": "sage",
	    "name": "Sage",
	    "hp": 8,
	    "skills": 6,
	    "kom": ["Int", "Cha", "Wis"],
	    "kdm": ["Str", "Dex", "Con"],
	    "ab": "Low",
	    "highSaves": ["Any", "Any"],
	    "lowSave": "Any",
	    "fastTrack": ["Arcane Secrets"],
	    "mediumTrack": ["Just Blade", "Arcane Lore"],
	    "slowTrack": ["Force of Will"]
	},
	{
	    "id": "shaman",
	    "name": "Shaman",
	    "hp": 8,
	    "skills": 6,
	    "kom": "Wis",
	    "kdm": "Cha",
	    "ab": "Low",
	    "highSaves": ["Fort", "Will"],
	    "lowSave": "Ref",
	    "fastTrack": ["Spellcasting"],
	    "mediumTrack": ["Incantation"],
	    "slowTrack": "Any"
	},
	{
	    "id": "tactician",
	    "name": "Tactician",
	    "hp": 8,
	    "skills": 9,
	    "kom": "Int",
	    "kdm": "Con",
	    "ab": "Low",
	    "highSaves": ["Ref", "Will"],
	    "lowSave": "Fort",
	    "fastTrack": ["Spellcasting"],
	    "mediumTrack": ["Tactical Insight"],
	    "slowTrack": ["Bag of Tricks"]
	}
]